[package]
name = "mod-template"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
conflux = { path = "../conflux", features = ["minijinja", "serde"] }
mom = { path = "../mom", features = ["serde"] }
search = { path = "../search" }

# impl deps
closest = { path = "../closest", optional = true }
form_urlencoded = { version = "1.2.1", optional = true }
html-escape = { version = "0.2.13", optional = true }
itertools = { version = "0.13.0", optional = true }
rand = { version = "0.8.5", optional = true }
serde_json = { version = "1.0.140", optional = true }
urlencoding = { version = "2.1.3", optional = true }
minijinja = { version = "2.8.0", features = [
    "loader",
    "debug",
], optional = true }
config = { path = "../config" }
highlight = { path = "../highlight", optional = true }
credentials = { path = "../credentials", features = ["serde"] }
htmlrewrite = { path = "../htmlrewrite", optional = true }
time = { version = "0.3.41", features = [
    "formatting",
    "parsing",
], optional = true }
merde = { workspace = true, features = ["time"], optional = true }
dylo-runtime = "2.5.0"
image = { version = "0.1.0", path = "../image", optional = true }
media = { version = "0.1.0", path = "../media", optional = true }
noteyre = { version = "0.1.0", path = "../noteyre" }
markdown = { version = "0.1.0", path = "../markdown", optional = true }
camino = "1.1.9"
percent-encoding = "2.3.1"

[dev-dependencies]
insta = "1.42.2"

[features]
default = ["impl"]
impl = [
    "dep:minijinja",
    "dep:highlight",
    "dep:closest",
    "dep:form_urlencoded",
    "dep:html-escape",
    "dep:itertools",
    "dep:rand",
    "dep:serde_json",
    "dep:urlencoding",
    "dep:htmlrewrite",
    "dep:time",
    "dep:merde",
    "dep:image",
    "dep:media",
    "dep:markdown",
]
