[package]
name = "librevision"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
atomicwrites = { version = "0.4.4" }
camino = { version = "1.1.11" }
closest = { version = "0.1.0", path = "../closest" }
conflux = { version = "0.1.0", path = "../../crates/conflux" }
content-type = { version = "0.1.0", path = "../content-type" }
cub-types = { version = "0.1.0", path = "../cub-types" }
derivations = { version = "0.1.0", path = "../derivations" }
liberrhandling = { version = "0.1.0", path = "../liberrhandling" }
eyre.workspace = true
facet-json.workspace = true
facet-pretty.workspace = true
libfs = { version = "0.1.0", path = "../libfs" }
futures-core = "0.3.31"
libimage = { version = "0.1.0", path = "../libimage" }
itertools = { version = "0.14.0" }
libmarkdown = { version = "0.1.0", path = "../libmarkdown" }
rayon = { version = "1.11.0" }
redb = { version = "2.6.3" }
seahash = { version = "4.1.0" }
libsearch = { version = "0.1.0", path = "../libsearch" }
libsvg = { version = "0.1.0", path = "../libsvg" }
libtemplate = { version = "0.1.0", path = "../libtemplate" }
time = { version = "0.3.41" }
tokio = { workspace = true }
uffmpeg = { version = "0.1.0", path = "../../crates/uffmpeg" }
ulid = { version = "1.2.1" }
wildmatch = { version = "2.4.0" }
config-types = { version = "0.1.0", path = "../config-types" }
image-types = { version = "0.1.0", path = "../image-types" }
template-types = { version = "0.1.0", path = "../template-types" }
markdown-types = { version = "0.1.0", path = "../markdown-types" }
autotrait = "0.2.1"
fs-err = { version = "3.1.1", features = ["tokio"] }
facet.workspace = true
facet-yaml.workspace = true
log = "0.4.27"
