[package]
name = "mod-api"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
# impl-only dependencies
dylo = { workspace = true, optional = true }
url = { version = "2.5.4", optional = true }
reddit = { version = "0.1.0", path = "../reddit", optional = true }
tracing = { workspace = true, optional = true }

# core dependencies
hattip = { version = "0.1.0", path = "../hattip" }
cub-types = { version = "0.1.0", path = "../cub-types" }
dylo-runtime = "2.5.0"

[features]
default = ["impl"]
impl = ["dep:url", "dep:dylo", "dep:reddit", "dep:tracing"]
