[package]
name = "uffmpeg"
version = "0.1.0"
edition = "2024"

[dependencies]
camino = "1.1.9"
conflux = { version = "0.1.0", path = "../conflux" }
eyre.workspace = true
ffmpeg-sidecar = "2.0.6"
image-types = { version = "0.1.0", path = "../image-types" }
tokio.workspace = true
