[package]
name = "mod-clap"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
camino = { version = "1.1.9" }
dylo.workspace = true

# impl deps
clap = { version = "4.5.34", features = ["derive"], optional = true }
dylo-runtime = "2.5.0"

[features]
default = ["impl"]
impl = ["dep:clap"]
