[package]
name = "mod-github"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
eyre = { version = "0.6.12", default-features = false }
merde.workspace = true
config = { path = "../config" }

# impl deps
httpclient = { path = "../httpclient", features = ["json"] }
credentials = { path = "../credentials" }
fs-err = { version = "3.1.0", optional = true }
time = { version = "0.3.41", optional = true }
tracing = { version = "0.1.41", optional = true }
url = { version = "2.5.4", optional = true }
dylo-runtime = "2.5.0"
futures-core = "0.3.31"

[features]
default = ["impl"]
impl = ["dep:fs-err", "dep:time", "dep:tracing", "dep:url"]
