[package]
name = "sentrywrap"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
config-types = { version = "0.1.0", path = "../config-types" }
sentry = "0.42.0"
