[package]
name = "mod-lightningcss"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true

# impl dependencies
lightningcss = { version = "1.0.0-alpha.65", features = ["browserslist"] }
dylo-runtime = "2.5.0"

[features]
default = ["impl"]
impl = []
