[package]
name = "libwebsock"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
libhttpclient = { version = "0.1.0", path = "../libhttpclient" }
rubicon = "3.4.9"
http = { version = "1.3.1" }
hickory-resolver = { version = "0.24.4" }
tokio-tungstenite = { version = "0.23.1", features = [
    "rustls-tls-native-roots",
] }
tracing = { version = "0.1.41" }
tokio = { version = "1.44", features = ["fs"] }
futures-util = { version = "0.3.31" }
rustls = { version = "0.23", features = ["ring"], default-features = false }
futures-core = "0.3.31"
autotrait = "0.2.0"
fs-err = { version = "3.1.0", features = ["tokio"] }
