[package]
name = "mod-highlight"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
# impl dependencies
dumbcache = { path = "../dumbcache", optional = true }
tracing = { version = "0.1.41", optional = true }
tree-sitter-collection = { git = "https://github.com/bearcove/home-tree-sitter", optional = true }
nerdfonts = { path = "../nerdfonts", optional = true }
dylo-runtime = "2.5.0"


[features]
default = ["impl"]
impl = [
    "dep:dumbcache",
    "dep:tracing",
    "dep:tree-sitter-collection",
    "dep:nerdfonts",
]
