[package]
name = "mod-mom"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
camino = { version = "1.1.9" }
conflux = { path = "../conflux", features = ["rusqlite"] }
merde = { workspace = true, features = ["json", "rusqlite", "serde", "camino"] }
config = { path = "../config", features = ["serde"] }
errhandling = { path = "../errhandling", optional = true }
httpclient = { path = "../httpclient", features = ["json"], optional = true }
objectstore = { path = "../objectstore", features = ["rusqlite"] }
term = { path = "../term", optional = true }
credentials = { path = "../credentials", optional = true }
patreon = { path = "../patreon", optional = true }
github = { path = "../github", optional = true }
content-type = { path = "../content-type", optional = true }
derivations = { version = "0.1.0", path = "../derivations" }

# impl deps
async-trait = { version = "0.1.88", optional = true }
axum = { version = "0.7.9", default-features = false, features = [
    "http1",
    "tokio",
    "ws",
    "query",
    "macros",
], optional = true }
eyre = { version = "0.6.12", default-features = false, optional = true }
futures-util = { version = "0.3.31", optional = true }
inflight = { path = "../inflight", optional = true }
parking_lot = { version = "0.12.3", optional = true }
r2d2 = { version = "0.8.10", optional = true }
r2d2_sqlite = { version = "0.25.0", optional = true }
rusqlite = { workspace = true, default-features = false, features = [
    "time",
], optional = true }
serde = { version = "1.0.219", features = ["derive"], optional = true }
time = { version = "0.3.41", features = ["formatting"], optional = true }
tokio = { version = "1.44.1", features = ["full"] }
tracing = { version = "0.1.41", optional = true }
url = { version = "2.5.4", optional = true }
dylo-runtime = "2.5.0"
tempfile = { version = "3.19.1", optional = true }
ffmpeg-sidecar = { version = "2.0.5", optional = true }
nix = { version = "0.29.0", features = ["process", "signal"], optional = true }
tokio-stream = { version = "0.1.17", optional = true }
image = { version = "0.1.0", path = "../image" }
uffmpeg = { version = "0.1.0", path = "../uffmpeg", optional = true }
svg = { version = "0.1.0", path = "../svg", optional = true }
bytesize = { version = "1.3.2", optional = true }
noteyre = { version = "0.1.0", path = "../noteyre" }
futures-core = "0.3.31"
owo-colors = "4.2.0"
itertools = "0.14.0"

[features]
default = ["impl"]
impl = [
    "dep:async-trait",
    "dep:axum",
    "dep:eyre",
    "dep:futures-util",
    "dep:inflight",
    "dep:parking_lot",
    "dep:r2d2",
    "dep:r2d2_sqlite",
    "dep:rusqlite",
    "dep:serde",
    "dep:time",
    "dep:tracing",
    "dep:url",
    "dep:content-type",
    "dep:credentials",
    "dep:errhandling",
    "dep:github",
    "dep:httpclient",
    "dep:patreon",
    "dep:term",
    "dep:tempfile",
    "dep:ffmpeg-sidecar",
    "dep:nix",
    "dep:tokio-stream",
    "dep:uffmpeg",
    "dep:svg",
    "dep:bytesize",
]
serde = ["dep:serde"]
