[package]
name = "libhtmlrewrite"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
autotrait = "0.1.8"

# impl deps
lol_html = { version = "1.2.1" }

[features]
default = ["impl"]
impl = []
