[package]
name = "mod-config"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
camino = { version = "1.1.9" }

# impl dependencies
fs-err = { version = "2.11.0", optional = true }
dotenvy = { version = "0.15.7", optional = true }
figment = { version = "0.10.19", features = ["env", "json"], optional = true }
serde = { version = "1.0.219", optional = true, features = ["derive"] }
plait = { path = "../plait" }
merde = { workspace = true, features = ["camino"] }
dylo-runtime = "2.5.0"
noteyre = { version = "0.1.0", path = "../noteyre" }
base64 = "0.22.1"
serde_json = { version = "1.0.140", optional = true }
owo-colors = { version = "4.2.0", optional = true }
facet.workspace = true
facet-json = "0.11.1"
facet-pretty = "0.13.0"

[features]
default = ["impl"]
serde = ["dep:serde", "camino/serde1"]
impl = [
    "dep:dotenvy",
    "dep:figment",
    "dep:fs-err",
    "serde",
    "dep:serde_json",
    "dep:owo-colors",
]
