[package]
name = "mod-compress"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
bytes = "1.10.1"

# impl deps
brotli = { version = "6.0.0", optional = true }
flate2 = { version = "1.1.0", optional = true }
dylo-runtime = "2.5.0"

[features]
default = ["impl"]
impl = ["dep:brotli", "dep:flate2"]
