[package]
name = "libdiscord"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
autotrait = "0.2.1"
config-types = { version = "0.1.0", path = "../config-types" }
credentials = { version = "0.1.0", path = "../credentials" }
eyre.workspace = true
facet.workspace = true
facet-json.workspace = true
futures-core = "0.3.31"
libhttpclient = { version = "0.1.0", path = "../libhttpclient" }
log = "0.4.27"
time = "0.3.41"
url = "2.5.7"
