[package]
name = "mod-cdn"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
# impl-only dependencies
bytesize = { version = "2.0.1", optional = true }
config = { version = "0.1.0", path = "../config", optional = true }
conflux = { version = "0.1.0", path = "../conflux", optional = true }
content-type = { version = "0.1.0", path = "../content-type", optional = true }
derivations = { version = "0.1.0", path = "../derivations", optional = true }
dylo = { workspace = true, optional = true }
http-range = { version = "0.1.5", optional = true }
libhttpclient = { version = "0.1.0", path = "../../libs/libhttpclient" }
mom = { version = "0.1.0", path = "../mom", optional = true }
noteyre = { version = "0.1.0", path = "../noteyre", optional = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
websock = { version = "0.1.0", path = "../websock", optional = true }

# core dependencies
hattip = { version = "0.1.0", path = "../hattip" }
cub-types = { version = "0.1.0", path = "../cub-types" }
dylo-runtime = "2.5.0"
futures-core = "0.3.31"

[features]
default = ["impl"]
impl = [
    "dep:bytesize",
    "dep:config",
    "dep:conflux",
    "dep:content-type",
    "dep:derivations",
    "dep:dylo",
    "dep:http-range",
    "dep:mom",
    "dep:noteyre",
    "dep:tokio",
    "dep:tracing",
    "dep:websock",
]
