[package]
name = "inflight"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = { version = "0.6.12", default-features = false }
futures-util = "0.3.31"
parking_lot = "0.12.3"
tokio = { version = "1.44.2", features = ["macros", "rt", "sync", "time"] }
