[package]
name = "mod-htmlrewrite"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true

# impl deps
lol_html = { version = "1.2.1", optional = true }
dylo-runtime = "2.5.0"

[features]
default = ["impl"]
impl = ["dep:lol_html"]
