[package]
name = "credentials"
version = "0.1.0"
edition = "2024"

[dependencies]
time = "0.3.41"
serde = { workspace = true, features = ["derive"] }
eyre.workspace = true
facet.workspace = true

[features]
