[package]
name = "credentials"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
eyre.workspace = true
facet.workspace = true
plait = { version = "0.1.0", path = "../plait" }
minijinja.workspace = true
rusqlite.workspace = true

[features]
