[package]
name = "mod-httpclient"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = "1.10.1"
dylo.workspace = true
futures-core = "0.3.31"
merde.workspace = true
form_urlencoded = { version = "1.2.1" }

# impl deps
futures-util = { version = "0.3.31", optional = true }
reqwest = { version = "0.12.15", features = [
    "h2",
    "rustls-tls",
    "stream",
], default-features = false, optional = true }
tokio-proxy = { path = "../tokio-proxy", optional = true }
dylo-runtime = "2.5.0"
http = "1.3.1"

[features]
default = ["impl"]
impl = [
    "dep:futures-util",
    "dep:reqwest",
    "dep:tokio-proxy",
    "merde/serialize",
    "merde/deserialize",
    "merde/json",
]
json = ["merde/serialize", "merde/deserialize", "merde/json"]
