[unstable]
mtime-on-use = true
binary-dep-depinfo = true
checksum-freshness = true
feature-unification = true

[resolver]
feature-unification = "workspace"

[build]
rustflags = [
    # "-Cprefer-dynamic",
    "-Zshare-generics=y",
    "-Wunused-crate-dependencies",
    # "-Zunstable-options",
    # "--extern",
    # "force:std",
]

[patch.crates-io]
# facet = { path = "../../facet-rs/facet/facet" }
# facet-core = { path = "../../facet-rs/facet/facet-core" }
# facet-json = { path = "../../facet-rs/facet/facet-json" }
# facet-args = { path = "../../facet-rs/facet/facet-args" }
# facet-pretty = { path = "../../facet-rs/facet/facet-pretty" }
# facet-reflect = { path = "../../facet-rs/facet/facet-reflect" }
# facet-yaml = { path = "../../facet-rs/facet/facet-yaml" }
# facet-deserialize = { path = "../../facet-rs/facet/facet-deserialize" }
