[unstable]
mtime-on-use = true
binary-dep-depinfo = true
checksum-freshness = true
feature-unification = true

[resolver]
feature-unification = "workspace"

[patch.crates-io]
# facet = { path = "../facet/facet" }
# facet-core = { path = "../facet/facet-core" }
# facet-json = { path = "../facet/facet-json" }
# facet-pretty = { path = "../facet/facet-pretty" }
