[unstable]
mtime-on-use = true
binary-dep-depinfo = true
checksum-freshness = true
feature-unification = true

[resolver]
feature-unification = "workspace"

[build]
rustflags = [
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
    "-Zunstable-options",
    "-Wunused-crate-dependencies",
    "--extern",
    "force:std",
]
