[unstable]
mtime-on-use = true
binary-dep-depinfo = true
checksum-freshness = true
feature-unification = true

[resolver]
feature-unification = "workspace"

[build]
rustflags = [
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
    "-Cprefer-dynamic",
    "-Zunstable-options",
    "--extern",
    "force:std",
]

[patch.crates-io]
# facet = { path = "../facet/facet" }
# facet-core = { path = "../facet/facet-core" }
# facet-json = { path = "../facet/facet-json" }
# facet-pretty = { path = "../facet/facet-pretty" }
