[package]
name = "mod-objectstore"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
futures-util = "0.3.31"
bytes = "1"
rubicon = "3.4.9"

# impl deps
object_store = { version = "0.10.2", features = ["aws"], optional = true }
tokio-proxy = { path = "../tokio-proxy", optional = true }
tracing = { version = "0.1.41", optional = true }
tokio = { version = "1.44", optional = true, features = [] }
config = { path = "../config" }
merde.workspace = true
rusqlite = { workspace = true, optional = true }
plait = { path = "../plait" }
dylo-runtime = "2.5.0"
futures-core = "0.3.31"
facet.workspace = true

[features]
default = ["impl"]
impl = ["object_store", "tokio", "tokio-proxy", "tracing"]
rusqlite = ["dep:rusqlite"]
