[package]
name = "tokio-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = { version = "0.6.12", default-features = false }
tokio = { version = "1.44.1", features = ["full"] }
tracing = { version = "0.1.41", features = [] }
