[package]
name = "mod-doctor"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo = { workspace = true }
dylo-runtime = "2.5.0"
futures-core = "0.3.31"
http = "1.3.1"
tokio = { workspace = true }

[features]
default = ["impl"]
impl = []
