[package]
name = "plait"
version = "0.1.0"
edition = "2024"
[dependencies]
facet = { version = "0.16.0", workspace = true }

[dev-dependencies]
merde = { workspace = true, features = ["serialize", "deserialize", "json"] }
rusqlite.workspace = true
serde = { version = "1.0.219", features = ["derive"] }
