[package]
name = "libclap"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
autotrait = "0.1.12"
camino = { version = "1.1.9" }
clap = { version = "4.5.37", features = ["derive"] }
