[package]
name = "libclap"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
autotrait = "0.2.1"
camino = { version = "1.1.11" }
clap = { version = "4.5.45", features = ["derive"] }
