[package]
name = "libclap"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
autotrait = "0.1.11"
camino = { version = "1.1.9" }
clap = { version = "4.5.34", features = ["derive"] }
