[package]
name = "mod-tracingsub"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
tracing-subscriber = { version = "0.3.19", optional = true }
dylo-runtime = "2.5.0"
env_logger = "0.11.8"

[features]
default = ["impl"]
impl = ["dep:tracing-subscriber"]
