[package]
name = "mod-reddit"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
config = { path = "../config" }
httpclient = { path = "../httpclient", features = ["json"], optional = true }

# impl deps
merde = { workspace = true, optional = true }
tracing = { version = "0.1", optional = true }
url = { version = "2.5.4", optional = true }
dylo-runtime = "2.5.0"
noteyre = { version = "0.1.0", path = "../noteyre" }
futures-core = "0.3.31"

[features]
default = ["impl"]
impl = ["dep:merde", "dep:tracing", "dep:url", "dep:httpclient"]
