[package]
name = "mod-reddit"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
config = { path = "../config" }
libhttpclient = { path = "../../libs/libhttpclient" }

# impl deps
merde = { workspace = true }
tracing = { version = "0.1" }
url = { version = "2.5.4" }
dylo-runtime = "2.5.0"
noteyre = { version = "0.1.0", path = "../noteyre" }
futures-core = "0.3.31"

[features]
default = ["impl"]
impl = []
