[package]
name = "mod-markdown"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
conflux = { path = "../conflux" }

# impl dependencies
html-escape = { version = "0.2.13" }
pulldown-cmark = { version = "0.11.3", features = ["simd"] }
saphyr = { version = "0.0.1", default-features = false }
slug = { version = "0.1.6" }
template-types = { path = "../template-types" }
highlight = { path = "../highlight" }
math = { path = "../math" }
dylo.workspace = true
dylo-runtime = "2.5.0"
config = { version = "0.1.0", path = "../config" }
media = { version = "0.1.0", path = "../media" }
noteyre = { version = "0.1.0", path = "../noteyre" }

[dev-dependencies]
indoc = "2.0.6"
insta = "1.42.2"

[features]
default = ["impl"]
impl = []
