[package]
name = "libreddit"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
libhttpclient = { path = "../libhttpclient" }
tracing = { version = "0.1" }
url = { version = "2.5.4" }
futures-core = "0.3.31"
eyre.workspace = true
autotrait = "0.2.1"
config-types = { version = "0.1.0", path = "../config-types" }
facet.workspace = true
