[package]
name = "libfs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
eyre = { version = "0.6.12", default-features = false }
camino = { version = "1.1.11" }
ignore = { version = "0.4.23" }
notify = { version = "8.2.0" }
autotrait = "0.2.1"

[features]
default = []
