[package]
name = "libcompress"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
bytes = "1.10.1"
brotli = { version = "6.0.0" }
flate2 = { version = "1.1.0" }
autotrait = "0.1.10"
