[package]
name = "libhttpclient"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
autotrait = "0.2.1"
bytes = "1.10.1"
eyre.workspace = true
facet.workspace = true
facet-json.workspace = true
facet-reflect = "0.28.1"
form_urlencoded = "1.2.2"
futures-core = "0.3.31"
futures-util = "0.3.31"
http = "1.3.1"
mom-types = { version = "0.1.0", path = "../mom-types" }
reqwest = { version = "0.12.23", default-features = false, features = [
    "rustls-tls-native-roots",
] }
reqwest-middleware = "0.4.2"
reqwest-retry = "0.7.0"
