[package]
name = "mod-errhandling"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
eyre = { version = "0.6.12", default-features = false }

# impl dependencies
color-backtrace = { version = "0.7.0", default-features = false, features = [
    "use-backtrace-crate",
], optional = true }
color-eyre = { version = "0.6.3", default-features = false, features = [
    "track-caller",
], optional = true }
termcolor = { version = "1.4.1", optional = true }
dylo-runtime = "2.5.0"

[features]
default = ["impl"]
impl = ["dep:color-backtrace", "dep:color-eyre", "dep:termcolor"]
