[package]
name = "mod-term"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
clap = { path = "../clap" }

# impl deps
anstyle-parse = { version = "0.2.6", optional = true }
coolor = { version = "0.9.0", optional = true }
displaydoc = { version = "0.2.5", optional = true }
fs-err = { version = "2.11.0", optional = true }
nix = { version = "0.29.0", features = ["process"], optional = true }
owo-colors = { version = "4.2.0", optional = true }
portable-pty = { version = "0.8.1", optional = true }
shell-quote = { version = "0.6.1", optional = true }
term_size = { version = "0.3.2", optional = true }
termion = { version = "4.0.4", optional = true }
tracing = { version = "0.1.41", optional = true }
which = { version = "6.0.3", optional = true }
dylo-runtime = "2.5.0"

[features]
default = ["impl"]
impl = [
    "dep:anstyle-parse",
    "dep:coolor",
    "dep:displaydoc",
    "dep:fs-err",
    "dep:nix",
    "dep:owo-colors",
    "dep:portable-pty",
    "dep:shell-quote",
    "dep:term_size",
    "dep:termion",
    "dep:tracing",
    "dep:which",
]
