[package]
name = "liblightningcss"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
autotrait = "0.1.8"
eyre.workspace = true

# impl dependencies
lightningcss = { version = "1.0.0-alpha.65", features = ["browserslist"] }

[features]
default = ["impl"]
impl = []
