[package]
name = "libtemplate"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
conflux = { path = "../../crates/conflux" }
libmom = { path = "../libmom" }
libsearch = { path = "../libsearch" }
closest = { path = "../../crates/closest" }
form_urlencoded = { version = "1.2.1" }
html-escape = { version = "0.2.13" }
itertools = { version = "0.13.0" }
rand = { version = "0.8.5" }
serde_json = { version = "1.0.140" }
urlencoding = { version = "2.1.3" }
minijinja = { version = "2.8.0", features = ["loader", "debug"] }
libconfig = { path = "../libconfig" }
libhighlight = { path = "../libhighlight" }
credentials = { path = "../credentials" }
libhtmlrewrite = { path = "../libhtmlrewrite" }
time = { version = "0.3.41", features = ["formatting", "parsing"] }
merde = { workspace = true, features = ["time"] }
libimage = { version = "0.1.0", path = "../libimage" }
libmedia = { version = "0.1.0", path = "../libmedia" }
libmarkdown = { version = "0.1.0", path = "../libmarkdown" }
camino = "1.1.9"
percent-encoding = "2.3.1"
eyre.workspace = true
image-types = { version = "0.1.0", path = "../image-types" }
config-types = { version = "0.1.0", path = "../config-types" }
mom-types = { version = "0.1.0", path = "../mom-types" }
template-types = { version = "0.1.0", path = "../template-types" }

[dev-dependencies]
insta = "1.42.2"
