[package]
name = "mod-image"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true

# impl deps
image = { version = "0.25.6", default-features = false, features = [
    "jpeg",
    "png",
    "webp",
    "avif",
    "avif-native",
], optional = true }
ravif = { version = "0.11.11", optional = true }
rgb = { version = "0.8.50", optional = true }
webp = { version = "0.3.0", optional = true }
jxl-oxide = { version = "0.8.1", optional = true }
tracing = { version = "0.1.41", optional = true }
content-type = { path = "../content-type" }
dylo-runtime = "2.5.0"
merde = { workspace = true, features = ["time"] }
jpegxl-rs = { version = "0.11.2", features = ["vendored"], optional = true }
ordered-float = "4.6.0"
tempfile = { version = "3.19.1", optional = true }
fs-err = { version = "3.1.0", optional = true }
noteyre = { version = "0.1.0", path = "../noteyre" }
num_cpus = { version = "1.16.0", optional = true }

[features]
default = ["impl"]
impl = [
    "dep:image",
    "dep:ravif",
    "dep:rgb",
    "dep:webp",
    "dep:jxl-oxide",
    "dep:tracing",
    "dep:jpegxl-rs",
    "dep:tempfile",
    "dep:fs-err",
    "dep:num_cpus",
]
