name: build
on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]
  merge_group:
jobs:
  mac-build:
    runs-on: depot-macos-latest
    env:
      BEARDIST_CACHE_DIR: /tmp/cache/beardist
      BEARDIST_ARTIFACT_NAME: aarch64-apple-darwin
      GH_READWRITE_TOKEN: ${{ secrets.GH_READWRITE_TOKEN }}
      CLICOLOR: 1
      CLICOLOR_FORCE: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set default rustup toolchain
        run: |
          rustup default nightly-2025-04-23
          rustc --version
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: /tmp/cache
          key: ${{ runner.os }}-${{ matrix.artifact }}-home-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.artifact }}-home-
      - name: Download beardist
        run: |
          curl -L -o beardist.tar.xz https://github.com/bearcove/beardist/releases/download/v2.1.0/aarch64-apple-darwin.tar.xz
          tar -xf beardist.tar.xz
          chmod +x beardist
          sudo mv beardist /usr/local/bin/
      - name: Install required dependencies
        run: |
          # Install pnpm package manager and bun via tap
          brew tap oven-sh/bun
          brew install node pnpm cargo-sweep cargo-nextest just bun coreutils xz dav1d
      - name: Build
        run: |
          beardist build
  linux-build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - name: Set EXTRA_TAG if this is a Git tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            echo "EXTRA_TAG=ghcr.io/bearcove/home:${TAG_NAME}" >> $GITHUB_ENV
          else
            echo "EXTRA_TAG=" >> $GITHUB_ENV
          fi
      - name: Bake Docker images
        uses: depot/bake-action@v1
        with:
          lint: true
          files: docker-bake.hcl
  trigger-formula-update:
    needs: [mac-build] # TODO: restore linux build etc.
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger workflow dispatch for bump.yml
        run: |
          curl -X POST \
            -f \
            -H "Authorization: token ${{ env.GH_READWRITE_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{
              "ref": "main",
              "inputs": {}
            }' \
            https://api.github.com/repos/bearcove/homebrew-tap/actions/workflows/bump.yml/dispatches
