[package]
name = "mod-search"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
conflux = { path = "../conflux", features = [] }

# impl deps
eyre = { workspace = true, optional = true }
html-escape = { version = "0.2.13", optional = true }
indicium = { version = "0.6.5", features = [
    "simple",
], default-features = false, optional = true }
tantivy = { version = "0.22.0", optional = true }
tracing = { workspace = true, optional = true }
dylo-runtime = "2.5.0"
noteyre = { version = "0.1.0", path = "../noteyre" }
config = { version = "0.1.0", path = "../config" }
percent-encoding = "2.3.1"

[features]
default = ["impl"]
impl = [
    "dep:eyre",
    "dep:html-escape",
    "dep:indicium",
    "dep:tantivy",
    "dep:tracing",
]
