[package]
name = "mod-search"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
conflux = { path = "../conflux" }

# impl deps
eyre = { workspace = true }
html-escape = { version = "0.2.13" }
indicium = { version = "0.6.5", features = [
    "simple",
], default-features = false }
tantivy = { version = "0.22.0" }
tracing = { workspace = true }
dylo-runtime = "2.5.0"
noteyre = { version = "0.1.0", path = "../noteyre" }
config = { version = "0.1.0", path = "../config" }
percent-encoding = "2.3.1"

[features]
default = ["impl"]
impl = []
