[package]
name = "mod-patreon"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
dylo.workspace = true
eyre = { version = "0.6.12", default-features = false }
merde = { workspace = true, features = ["json"] }
config = { path = "../config" }
credentials = { path = "../credentials" }

# impl dependencies
fs-err = { version = "3.1.0", optional = true }
jsonapi = { version = "0.7.0", optional = true }
serde = { version = "1.0.219", features = ["derive"], optional = true }
serde_json = { version = "1.0.140", optional = true }
time = { version = "0.3.41", optional = true }
tracing = { version = "0.1.41", optional = true }
url = { version = "2.5.4", optional = true }
dylo-runtime = "2.5.0"
futures-core = "0.3.31"
libhttpclient = { version = "0.1.0", path = "../../libs/libhttpclient" }

[features]
default = ["impl"]
impl = [
    "dep:fs-err",
    "dep:jsonapi",
    "dep:serde",
    "dep:serde_json",
    "dep:time",
    "dep:tracing",
    "dep:url",
]
